[package]
name = "snd-firewire-ctl-services"
version = "0.1.0"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
edition = "2018"
license-file = "COPYING"

[lib]
name = "snd_fw_ctl_services"

[dependencies]
libc = "0.2"
nix = "0.17"
glib = "0.10"
hinawa = { git = "https://github.com/alsa-project/hinawa-rs.git", tag = "v0.3.0", version = "0.3" }
alsactl = { git = "https://github.com/alsa-project/alsa-gobject-rs.git", tag = "v0.1.1", version = "0.1" }
alsaseq = { git = "https://github.com/alsa-project/alsa-gobject-rs.git", tag = "v0.1.1", version = "0.1" }

[[bin]]
name = "snd-firewire-digi00x-ctl-service"
path = "src/bin/snd-firewire-digi00x-ctl-service.rs"

[[bin]]
name = "snd-firewire-tascam-ctl-service"
path = "src/bin/snd-firewire-tascam-ctl-service.rs"

[[bin]]
name = "snd-fireworks-ctl-service"
path = "src/bin/snd-fireworks-ctl-service.rs"

[[bin]]
name = "snd-firewire-motu-ctl-service"
path = "src/bin/snd-firewire-motu-ctl-service.rs"

[[bin]]
name = "snd-oxfw-ctl-service"
path = "src/bin/snd-oxfw-ctl-service.rs"

[[bin]]
name = "snd-bebob-ctl-service"
path = "src/bin/snd-bebob-ctl-service.rs"
