[workspace]
members = [
    "libs/alsa-ctl-tlv-codec",
    "libs/core",
    "libs/ieee1212-config-rom",
    "libs/ta1394",
    "libs/dg00x",
    "libs/tascam",
    "libs/efw",
    "libs/motu",
    "libs/oxfw",
    "libs/bebob",
    "libs/dice/protocols",
    "services",
]
