[workspace]
members = [
    "libs/core",
    "libs/ieee1212",
    "libs/ta1394",
    "libs/dg00x",
    "libs/tascam",
    "libs/efw",
    "libs/motu",
    "libs/oxfw",
    "libs/bebob",
    "services",
]
