[package]
edition = "2018"
name = "snd-firewire-ctl-services"
version = "0.1.0"
# For publishing.
authors = ["Takashi Sakamoto"]
description = """
Service programs to control audio and music unit on IEEE 1394 bus, supported by ALSA
"""
license = "GPL-3.0-or-later"

[dependencies]
libc = "0.2"
glib = "0.10"
alsactl = "0.3"
alsaseq = { git = "https://github.com/alsa-project/alsa-gobject-rs.git", tag = "v0.3.0", version = "0.3" }
hinawa = "0.5"
hitaki = "0.1"
core = { path = "libs/core" }
dg00x-runtime = { path = "libs/dg00x/runtime" }
tascam-runtime = { path = "libs/tascam/runtime" }
efw-runtime = { path = "libs/efw/runtime" }
motu-runtime = { path = "libs/motu/runtime" }
oxfw-runtime = { path = "libs/oxfw/runtime" }
bebob-runtime = { path = "libs/bebob/runtime" }
dice-runtime = { path = "libs/dice/runtime" }
ff-runtime = { path = "libs/ff/runtime" }

[workspace]
members = [
    "libs/alsa-ctl-tlv-codec",
    "libs/core",
    "libs/ieee1212-config-rom",
    "libs/ta1394",
    "libs/dg00x/protocols",
    "libs/dg00x/runtime",
    "libs/tascam/protocols",
    "libs/tascam/runtime",
    "libs/efw/protocols",
    "libs/efw/runtime",
    "libs/motu/protocols",
    "libs/motu/runtime",
    "libs/oxfw/protocols",
    "libs/oxfw/runtime",
    "libs/bebob/protocols",
    "libs/bebob/runtime",
    "libs/dice/protocols",
    "libs/dice/runtime",
    "libs/ff/protocols",
    "libs/ff/runtime",
]

# They have plans to be published into crates.io.
[patch.crates-io]
hinawa = { git = "https://github.com/alsa-project/hinawa-rs.git", tag = "v0.5.2" }
hitaki = { git = "https://github.com/alsa-project/hitaki-rs.git", tag = "v0.1.0" }
alsactl = { git = "https://github.com/alsa-project/alsa-gobject-rs.git", tag = "v0.3.0" }
