[workspace]
members = [
    "libs/alsa-ctl-tlv-codec",
    "libs/core",
    "libs/ieee1212-config-rom",
    "libs/ta1394",
    "libs/dg00x",
    "libs/tascam",
    "libs/efw",
    "libs/motu/runtime",
    "libs/oxfw/protocols",
    "libs/oxfw/runtime",
    "libs/bebob",
    "libs/dice/protocols",
    "libs/dice/runtime",
    "libs/ff/protocols",
    "libs/ff/runtime",
    "services",
]
