[package]
edition = "2018"
name = "core"
version = "0.1.0"
# For publishing.
authors = ["Takashi Sakamoto"]
description = """
Core utilities to produce service programs for ALSA control and sequencer applications
"""
license = "GPL-3.0-or-later"
publish = false

[dependencies]
libc = "0.2"
nix = "0.17"
glib = "0.15"
hinawa = "0.7"
hitaki = "0.2"
alsactl = "0.4"
alsaseq = "0.4"
clap = { version = "3.2", features = ["derive"] }
